<?php

namespace InscripcionBundle\Entity\Repository;

/**
 * InstitucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucionRepository extends \Doctrine\ORM\EntityRepository
{
}
