<?php

namespace InscripcionBundle\Entity\Repository;

/**
 * PlanillaEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanillaEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
