<?php

namespace SeguridadBundle\Entity\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository
{
    public function dataTable($request)
    {
        return array(
                      "total"    => $this->getTotalRows(),
                      "filtered" => $this->getFilteredRows($request),
                      "rows"     => $this->getRows($request)
            );
    }
    
    public function getRows($request)
    {
        $columns = ["p.id","p.name","p.description","p.isActive"];
                
        return $this->getEntityManager()
                        ->createQuery(" SELECT p
                                        FROM SeguridadBundle:Cargo p
                                        WHERE (p.name LIKE ?1) OR (p.description LIKE ?1)
                                        ORDER BY ".$columns[$request->get('order')[0]['column']]." ".$request->get('order')[0]['dir']) 
                        ->setParameter(1,'%'.$request->get('search')['value'].'%')
                        ->setMaxResults($request->get('length'))
                        ->setFirstResult($request->get('start'))
                        ->getResult();
    }
    
    public function getFilteredRows($request)
    {
        return $this->getEntityManager()
                        ->createQuery(" SELECT COUNT(p)
                                        FROM SeguridadBundle:Cargo p
                                        WHERE (p.name LIKE ?1) OR (p.description LIKE ?1) ")
                        ->setParameter(1,'%'.$request->get('search')['value'].'%')
                        ->getSingleScalarResult();
    }
    
    public function getTotalRows()
    {
        return $this->getEntityManager()
                        ->createQuery(" SELECT COUNT(u)
                                        FROM SeguridadBundle:Cargo u
                                       ")
                        ->getSingleScalarResult();
    }
}
