<?php

namespace SeguridadBundle\Entity\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function dataTable($request,$user,$canViewAll)
    {
        return array(
                      "total"    => $this->getTotalRows($user,$canViewAll),
                      "filtered" => $this->getFilteredRows($request,$user,$canViewAll),
                      "rows"     => $this->getRows($request,$user,$canViewAll)
            );
    }
    
    public function getRows($request,$user,$canViewAll)
    {
        $columns = ["u.id","u.ico","u.username","p.apellido","p.dni","u.isActive","info","pass","actions"];
        $where = "(u.username LIKE ?1 OR p.apellido LIKE ?1 OR p.nombre LIKE ?1 OR p.dni LIKE ?1)";
                
        if (!$canViewAll){
            $where .= " AND (m.id = " . $user->getPersona()->getMunicipio()->getId() . ")";
        }
        return $this->getEntityManager()
                        ->createQuery(" SELECT u
                                        FROM SeguridadBundle:Usuario u
                                        JOIN u.persona p
                                        JOIN p.municipio m
                                        WHERE $where
                                        ORDER BY ".$columns[$request->get('order')[0]['column']]." ".$request->get('order')[0]['dir'])
                        ->setParameter(1,'%'.$request->get('search')['value'].'%')
                        ->setMaxResults($request->get('length'))
                        ->setFirstResult($request->get('start'))
                        ->getResult();
    }
    
    public function getFilteredRows($request,$user,$canViewAll)
    {
        $where = "(u.username LIKE ?1 OR p.apellido LIKE ?1 OR p.nombre LIKE ?1 OR p.dni LIKE ?1)";
                
        if (!$canViewAll){
            $where .= " AND (m.id = " . $user->getPersona()->getMunicipio()->getId() . ")";
        }
        return $this->getEntityManager()
                        ->createQuery(" SELECT COUNT(u)
                                        FROM SeguridadBundle:Usuario u
                                        JOIN u.persona p
                                        JOIN p.municipio m
                                        WHERE $where ")
                        ->setParameter(1,'%'.$request->get('search')['value'].'%')
                        ->getSingleScalarResult();
    }
    
    public function getTotalRows($user,$canViewAll)
    {
        $where = "1 = 1";
        if (!$canViewAll){
            $where .= " AND (m.id = " . $user->getPersona()->getMunicipio()->getId() . ")";
        }
        return $this->getEntityManager()
                        ->createQuery(" SELECT COUNT(u)
                                        FROM SeguridadBundle:Usuario u
                                        JOIN u.persona p
                                        JOIN p.municipio m
                                        WHERE $where ")
                        ->getSingleScalarResult();
    }
    
    //
    //public function countActivos()
    //{
    //    return $this->getEntityManager()
    //                ->createQuery(" SELECT COUNT(u)
    //                                FROM SeguridadBundle:Usuario u
    //                                WHERE u.activo = ?1")
    //                ->setParameter(1,true)
    //                ->getSingleScalarResult();        
    //}
    //
    //public function countInactivos()
    //{
    //    return $this->getEntityManager()
    //                ->createQuery(" SELECT COUNT(u)
    //                                FROM SeguridadBundle:Usuario u
    //                                WHERE u.activo = ?1")
    //                ->setParameter(1,false)
    //                ->getSingleScalarResult();        
    //}    
}

