<?php

namespace SeguridadBundle\Entity\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    //public function dataTable($request)
    //{
    //    $columns = ["id","ico","usuario","apellido","dni","active","info","pass","actions"];
    //    return array(   "count" => $this->getEntityManager()
    //                                    ->createQuery(" SELECT COUNT(u)
    //                                                    FROM SeguridadBundle:Usuario u
    //                                                    WHERE u.usuario LIKE ?1 OR u.apellido LIKE ?1 OR u.nombre LIKE ?1 OR u.dni LIKE ?1")
    //                                    ->setParameter(1,'%'.$request->get('search')['value'].'%')
    //                                    ->getSingleScalarResult(),
    //                    "users" => $this->getEntityManager()
    //                                    ->createQuery(" SELECT u
    //                                                    FROM SeguridadBundle:Usuario u
    //                                                    WHERE u.usuario LIKE ?1 OR u.apellido LIKE ?1 OR u.nombre LIKE ?1 OR u.dni LIKE ?1
    //                                                    ORDER BY "."u.".$columns[$request->get('order')[0]['column']]." ".$request->get('order')[0]['dir'])
    //                                    ->setParameter(1,'%'.$request->get('search')['value'].'%')
    //                                    ->setMaxResults($request->get('length'))
    //                                    ->setFirstResult($request->get('start'))
    //                                    ->getResult()
    //        );
    //}
    //
    //public function count()
    //{
    //    return $this->getEntityManager()
    //                ->createQuery(" SELECT COUNT(u)
    //                                FROM SeguridadBundle:Usuario u
    //                                GROUP BY u.activo")
    //                ->getScalarResult();        
    //}
    //
    //public function countActivos()
    //{
    //    return $this->getEntityManager()
    //                ->createQuery(" SELECT COUNT(u)
    //                                FROM SeguridadBundle:Usuario u
    //                                WHERE u.activo = ?1")
    //                ->setParameter(1,true)
    //                ->getSingleScalarResult();        
    //}
    //
    //public function countInactivos()
    //{
    //    return $this->getEntityManager()
    //                ->createQuery(" SELECT COUNT(u)
    //                                FROM SeguridadBundle:Usuario u
    //                                WHERE u.activo = ?1")
    //                ->setParameter(1,false)
    //                ->getSingleScalarResult();        
    //}    
}

