common:
    resource: "@CommonBundle/Controller/"
    type:     annotation
    prefix:   /system
seguridad:
    resource: "@SeguridadBundle/Controller/"
    type:     annotation
    prefix:   /
gestion:
    resource: "@GestionBundle/Controller/"
    type:     annotation
    prefix:   /system
inscripcion:
    resource: "@InscripcionBundle/Controller/"
    type:     annotation
    prefix:   /inscripcion
resultado:
    resource: "@ResultadoBundle/Controller/"
    type:     annotation
    prefix:   /resultado
