<?php

namespace AcreditacionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AreaCategoriaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaCategoriaPagoRepository extends EntityRepository
{
}
