<?php

namespace AcreditacionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FuncionJuegosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionJuegosRepository extends EntityRepository {

    /**
     * Retorna las funciones asociadas a un area en aprticular cuyo id se proporciona como parámetro
     */
    public function getFuncionAreaId($idArea) {
        return $this->createQueryBuilder('f')
                        ->innerJoin('f.areasAbarcadas', 'area')
                        ->where('area.id = :param1')
                        ->setParameter('param1', $idArea)->getQuery()->getResult();
    }

    /**
     * 
     */
    public function esEliminable($idFuncion) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
        SELECT personal FROM AcreditacionBundle:PersonalJuegos personal
        INNER JOIN personal.funcion func
        WHERE func.id = :idFunc')->setParameter('idFunc', $idFuncion);
        $result = $query->getResult();
        return (count($result) > 0) ? false : true;
    }

}
