<?php

namespace AcreditacionBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JuegosParametrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuegosParametrosRepository extends EntityRepository
{
    
    /**
     * Retorne los acreditados de tipo gestion de un area determinada. El area se recibe como parámetro
     */
    public function getParam() {
        $result = $this->findAll(); 
        return (count($result) > 0) ? $result[0] : null;
    }
}
