<?php

namespace TesoreriaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatosTesoreriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosTesoreriaRepository extends EntityRepository
{
    public function datatable($request)
    {
        $columns = ["avatar","dp.apellido","dp.documentoNro","a.nombre","cat.monto + dt.pagoEspecifico","f.nombre","es.descripcion","actions"];
        $where = " WHERE a.nombre LIKE ?1 OR dp.nombre LIKE ?1 OR dp.apellido LIKE ?1 OR dp.documentoNro LIKE ?1 OR f.nombre LIKE ?1 OR f.abreviatura LIKE ?1 ";
        $str = explode(",",$request->get('search')['value']);
        
        if (isset($str[1]) && is_numeric($str[0])){
            $where = " WHERE (f.id = ".$str[0]." OR SIZE( dt.movimientos ) = 0) AND (a.nombre LIKE ?1 OR dp.nombre LIKE ?1 OR dp.apellido LIKE ?1 OR dp.documentoNro LIKE ?1 OR f.nombre LIKE ?1) ";
            $str = trim($str[1]);
        }
        else{
            $str = $request->get('search')['value'];
        }        
        return array(   "total" =>  $this->getEntityManager()
                                        ->createQuery(" SELECT COUNT(pj)
                                                        FROM AcreditacionBundle:PersonalJuegos pj")
                                        ->getSingleScalarResult(),
                        "count" =>  $this->getEntityManager()
                                        ->createQuery(" SELECT COUNT(pj)
                                                        FROM AcreditacionBundle:PersonalJuegos pj
                                                        JOIN pj.area a
                                                        JOIN pj.datosPersonales dp
                                                        JOIN pj.datosTesoreria dt
                                                        LEFT JOIN dt.movimientos mv
                                                        LEFT JOIN mv.estado es
                                                        LEFT JOIN mv.fondo f ". $where)
                                        ->setParameter(1,'%'.$str.'%')
                                        ->getSingleScalarResult(),
                        "data" =>   $this->getEntityManager()
                                        ->createQuery(" SELECT pj
                                                        FROM AcreditacionBundle:PersonalJuegos pj
                                                        JOIN pj.area a
                                                        JOIN pj.datosPersonales dp
                                                        JOIN pj.datosTesoreria dt
                                                        JOIN dt.categoriaPago cat
                                                        LEFT JOIN dt.movimientos mv
                                                        LEFT JOIN mv.estado es
                                                        LEFT JOIN mv.fondo f ". $where."
                                                        ORDER BY ".$columns[$request->get('order')[0]['column']]." ".$request->get('order')[0]['dir'])
                                                        
                                        ->setParameter(1,'%'.$str.'%')
                                        ->setMaxResults($request->get('length'))
                                        ->setFirstResult($request->get('start'))
                                        ->getResult()
            );
    }
}
