<?php

namespace TesoreriaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FondoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondoRepository extends EntityRepository
{
}
