<?php

namespace ResultadoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CompetidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetidorRepository extends EntityRepository
{
    public function getParticipanteSospechosos()
    {
        return $this->getEntityManager()
                        ->createQuery(' SELECT p
                                        FROM ResultadoBundle:Competidor p
                                        JOIN p.equipos e
                                        GROUP BY p.id
                                        HAVING COUNT(p.id) > 1
                                        ORDER BY p.apellido,p.nombre'
                                    )
                        ->getResult();
        ;
    }
    
    public function getCompetidorByDni($competidor)
    {
        return $this->getEntityManager()
                        ->createQuery(' SELECT p
                                        FROM ResultadoBundle:Competidor p 
                                        WHERE p.documentoNro = ?1 AND p.id <> ?2')
                        ->setParameter(1,$competidor->getDocumentoNro())
                        ->setParameter(2,$competidor->getId()?$competidor->getId():0)
                        ->getoneornullresult();
        ;
    }
    
    public function getNombresDpl()
    {
        return $this->getEntityManager()
                        ->createQuery(' SELECT p
                                        FROM ResultadoBundle:Competidor p
                                        WHERE  EXISTS (SELECT p1.id
                                                        FROM ResultadoBundle:Competidor p1
                                                        WHERE UPPER(p1.nombre) = UPPER(p.nombre) AND UPPER(p.apellido) = UPPER(p1.apellido) AND p.id <> p1.id
                                                    )
                                        ORDER BY p.apellido,p.nombre'
                                    )
                        ->getResult();
        ;
    }
    
    public function getDniMay99M()
    {
        return $this->getEntityManager()
                        ->createQuery(' SELECT p
                                        FROM ResultadoBundle:Competidor p
                                        WHERE p.documentoNro >99000000
                                        ORDER BY p.apellido,p.nombre'
                                    )
                        ->getResult();
        ;
    }
    
    public function getDniMen1M()
    {
        return $this->getEntityManager()
                        ->createQuery(' SELECT p
                                        FROM ResultadoBundle:Competidor p
                                        WHERE p.documentoNro < 1000000
                                        ORDER BY p.apellido,p.nombre'
                                    )
                        ->getResult();
        ;        
    }
}
