<?php

namespace ResultadoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AplicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaRepository extends EntityRepository
{
    public function getOnlyRoot()
    {
        return $this
                    ->createQueryBuilder('d')
                    ->where('d.padre IS NULL')
                    ->orderBy('d.nombre')
                    ->getQuery()->getResult();
    }
    
    public function getArbolAsArray($disciplinas = NULL)
    {
        if ($disciplinas == "All")
            $disciplinas = $this->getOnlyRoot();
        $resultado = array();
        foreach ($disciplinas as $item)
        {
            $aux = array();
            $aux['text']  = $item->getNombre();
            $aux['id']  = $item->getId();
            if (count($item->getHijos()))
            {
                $aux['children'] = $this->getArbolAsArray($item->getHijos());
                $aux['state'] = array('opened'=>true);
                $aux["icon"] = "fa fa-folder text-red fa-lg";
            }else
            {
                $aux["icon"] = "fa fa-thumb-tack text-green fa-lg";
            }
            $resultado[]=$aux;
        }
        
        return $resultado;
    }
}