<?php

namespace ResultadoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * TorneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlazaRepository extends EntityRepository
{
    public function getAllSinMedallero()
    {
        return $this->getEntityManager()
                        ->createQuery(" SELECT p
                                        FROM ResultadoBundle:Plaza p
                                        WHERE p NOT INSTANCE OF ResultadoBundle:PlazaMedallero")
                        ->getResult();
        ;
    }  
}